name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: azure-ci-cd-test

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod 777 ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Log in to Azure Registry
        run: |
          docker login \
          --username ${{ secrets.AZURE_REGISTRY_USERNAME }} \
          --password ${{ secrets.AZURE_REGISTRY_PASSWORD }} \
          ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}

      - name: Build and Push Image
        id: build-and-push-image
        env:
          IMAGE_TAG: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:${{ github.sha }}
        run: |
          docker image build -t $IMAGE_TAG .
          docker image push $IMAGE_TAG
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT