name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: azure-ci-cd-test
  CONTAINER_NAME: azure-ci-cd-test-app
  RESOURCE_GROUP_NAME: azure-ci-cd-test-rg

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod 777 ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Log in to the Container Registry
        run: |
          docker login \
            --username ${{ secrets.CONTAINER_REGISTRY_USERNAME }} \
            --password ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} \
            ${{ secrets.CONTAINER_REGISTRY_SERVER }}

      - name: Build and Push Image
        id: build-and-push-image
        env:
          IMAGE_TAG: ${{ secrets.CONTAINER_REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        run: |
          docker image build -t $IMAGE_TAG .
          docker image push $IMAGE_TAG
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT
          
      - name: Deploy Image
        uses: azure/cli@v2
        with:
          inlineScript: |
            az login --service-principal \
              --username ${{ secrets.AZURE_CLIENT_ID }} \
              --password ${{ secrets.AZURE_CLIENT_SECRET }} \
              --tenant ${{ secrets.AZURE_TENANT_ID }}
            az containerapp update \
              --name ${{ env.CONTAINER_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --image ${{ steps.build-and-push-image.outputs.image }}